name: Kodi
on:
- pull_request
- push
jobs:
  tests:
    name: Addon checker
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kodi-branch: [leia, matrix]
    steps:
    - uses: actions/checkout@v2
      with:
        path: ${{ github.repository }}
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get install xmlstarlet
        python -m pip install --upgrade pip packaging
        pip install kodi-addon-checker
    - name: Remove unwanted files
      run: awk '/export-ignore/ { print $1 }' .gitattributes | xargs rm -rf --
      working-directory: ${{ github.repository }}
    - name: Rewrite addon.xml for Matrix
      run: |
        xmlstarlet ed -L -u '/addon/requires/import[@addon="xbmc.python"]/@version' -v "3.0.0" addon.xml
        full_version=$(xmlstarlet sel -t -v 'string(/addon/@version)' addon.xml)
        version=${full_version%%+*}
        localversion_identifier=${full_version:${#version}}
        localversion_identifier=${localversion_identifier/+/_}
        xmlstarlet ed -L -u '/addon/@version' -v "$version+matrix$localversion_identifier" addon.xml
      working-directory: ${{ github.repository }}
      if: matrix.kodi-branch == 'matrix'
    - name: Run kodi-addon-checker
      run: kodi-addon-checker --branch=${{ matrix.kodi-branch }} ${{ github.repository }}/
