name: Release
on:
  push:
    tags:
    - 'v*'
jobs:
  build:
    name: Release service.upnext
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build zip files
        run: |
          sudo apt-get install xmlstarlet
          make multizip release=1
      - name: Get Leia filename
        id: get-leia-filename
        run: |
          echo "filename=$(cd ..;ls service.upnext*.zip | grep -v '+matrix.' | head -1)" >> $GITHUB_OUTPUT
      - name: Get Matrix filename
        id: get-matrix-filename
        run: |
          echo "filename=$(cd ..;ls service.upnext*+matrix.*.zip | head -1)" >> $GITHUB_OUTPUT
      - name: Get body
        id: get-body
        run: |
          description=$(sed '1,/^## Releases$/d;/## v[0-9\.]* ([0-9-]*)/d;/^$/,$d' README.md)
          echo $description
          description="${description//'%'/'%25'}"
          description="${description//$'\n'/'%0A'}"
          description="${description//$'\r'/'%0D'}" 
          echo "body=$description" >> $GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.get-body.outputs.body }}
          draft: false
          prerelease: false
      - name: Upload Leia zip
        id: upload-leia-zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: ${{ steps.get-leia-filename.outputs.filename }}
          asset_path: ../${{ steps.get-leia-filename.outputs.filename }}
          asset_content_type: application/zip
      - name: Upload Matrix zip
        id: upload-matrix-zip 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: ${{ steps.get-matrix-filename.outputs.filename }}
          asset_path: ../${{ steps.get-matrix-filename.outputs.filename }}
          asset_content_type: application/zip
      # - name: Generate distribution zip and submit to official kodi repository
        # id: kodi-addon-submitter
        # uses: xbmc/action-kodi-addon-submitter@v1.2
        # with:
          # kodi-repository: repo-scripts
          # kodi-version: leia
          # addon-id: service.upnext
          # kodi-matrix: true
        # env:
          # GH_USERNAME: ${{secrets.GH_USERNAME}}
          # GH_TOKEN: ${{secrets.GH_TOKEN}}
          # EMAIL: ${{secrets.EMAIL}}
